Add Large Gemm
KULeuven-MICAS/snax-gemm pull request #12
Opened 2023-10-20 11:21 UTC by xiaoling-yi

In this PR, we add the following:
* the source code of the Large Gemm
* the unit test of the Large Gemm
* the documentation of the Large Gemm

2023-10-20 12:17 UTC, rgantonio requested changes
Hi Xiaoling 🐔 

Please check the comments and some suggestions 🧨

2023-10-20 12:17 UTC, rgantonio commented on src/main/scala/gemm/LargeGemm.scala
> +  // Statemeny declaration
What is statemeny? or you meant state declaration?

2023-10-20 12:17 UTC, rgantonio commented on src/main/scala/gemm/Parameter.scala
> +  def InputMatrixBaseAddrA =
baseAddrIncrementA -> whatever fits 😄

2023-10-20 12:17 UTC, rgantonio commented on src/test/scala/gemm/MatrixlibLarge.scala
> +  def genRandSizeTest() = {
Small or large cap for first letter?

2023-10-20 12:17 UTC, rgantonio commented on src/test/scala/gemm/TestLargeGemm.scala
> +        dut.clock.step(5)
Please make into function! ⚰️

2023-10-20 12:17 UTC, rgantonio commented on src/test/scala/gemm/TestLargeGemm.scala
> +        dut.clock.step(5)
Make function too! If possible 🎧

2023-10-20 13:53 UTC, guilherme-paim requested changes
Heeey! Excelent job Xaoling ! 🤙😎 

Nice nice, in general, we need just to agree on variable nomenclature and a coding style.

2023-10-20 13:53 UTC, guilherme-paim commented on src/test/scala/gemm/TestLargeGemm.scala
> +        dut.clock.step(1)
This clock steps can have a comment, why 2, why 5 ..

2023-10-20 13:53 UTC, guilherme-paim commented on src/test/scala/gemm/TestLargeGemm.scala
> +// Simple large Gemm test to see if the control signals work well
You could describe better this test.
What are the limitations of the case tested here? 
N .. K ...
You set false -> true .. clock arbitrary cycles, ant there is no comment why you are doing that.

2023-10-20 13:53 UTC, guilherme-paim commented on src/test/scala/gemm/TestLargeGemm.scala
> +            MatrixlibLarge.LargeMarixMul_1D(
MatrixLibLarge

2023-10-20 13:53 UTC, guilherme-paim commented on src/test/scala/gemm/MatrixlibLarge.scala
> +object MatrixlibLarge {
MatrixLibLarge

you need to review your upper / lower cases

2023-10-20 13:53 UTC, guilherme-paim commented on src/test/scala/gemm/MatrixlibLarge.scala
> +  def genRandSizeTest() = {
GenRandSizeTest

2023-10-20 13:53 UTC, guilherme-paim commented on src/test/scala/gemm/MatrixlibLarge.scala
> +      Trans: Boolean
What is the purpose of this Trans variable?

2023-10-20 13:53 UTC, guilherme-paim commented on src/test/scala/gemm/TestLargeGemm.scala
> +          def check_output() = {
Consistency
This function should be CheckOutput()

2023-10-20 13:53 UTC, guilherme-paim commented on src/test/scala/gemm/MatrixlibLarge.scala
> +    var flattenedUInt_A = ""
you need to decide your notation on the upper and lower cases for variables
flattened_uint_A

2023-10-20 13:53 UTC, guilherme-paim commented on src/main/scala/gemm/Parameter.scala
>    def mul = input * 4
input what ? precision ? bitwidth?

2023-10-20 13:53 UTC, guilherme-paim commented on src/main/scala/gemm/Parameter.scala
> +  def DataWidthPerAddr = 8
why starting uppercase? DataWidthPerAddr -> dataWidthPerAddr

2023-10-20 13:53 UTC, guilherme-paim commented on src/test/scala/gemm/TestLargeGemm.scala
> +            val addr_slide_B = (dut.io.ctrl.addr_b_out
identation here

2023-10-20 13:53 UTC, guilherme-paim commented on src/test/scala/gemm/TestLargeGemm.scala
> +          dut.io.ctrl.addr_c_in.poke(start_addr_C)
a space here

2023-10-20 13:53 UTC, guilherme-paim commented on src/test/scala/gemm/TestLargeGemm.scala
> +          // Random generation of the matrices start address
space

2023-10-20 13:53 UTC, guilherme-paim commented on src/main/scala/gemm/Parameter.scala
>  object GEMMConstant {
GemmConstant

2023-10-20 13:53 UTC, guilherme-paim commented on README.md
>  <!-- This repository contains three GEMM versions: Base GEMM, Large GEMM, and Batch Large GEMM. -->
Block GEMM

2023-10-20 13:53 UTC, guilherme-paim commented on README.md
>  <!-- This repository contains three GEMM versions: Base GEMM, Large GEMM, and Batch Large GEMM. -->
Batch Block GEMM

2023-10-20 13:53 UTC, guilherme-paim commented on README.md
>  | input | Input matrix data width (integer) |
My general suggestion here is that you should have a style guide and maintain consistency for the:

1) run-time variables: input and outputs, and its suffix
2) design-time variables: architecture definitions, block sizes, and bitwidths
3) class names
4) function names
5) state variables

You need first to make a simple document or a repo: Chisel Style Guide with the decision on how you will maintain this consistency forever.

Input and output are too generic to be data width.
You could use a more clear nomenclature.
I also suggest thinking that A and B could have different precisions.

My suggestion is as follows:

dataWidthA
dataWidthB
dataWidthC
dataWidthAccum

2023-10-20 14:20 UTC, xiaoling-yi commented on README.md
> +| data_valid_i | 1 | In | Input data valid signal|
We don't have  data_valid_o because we use gemm_write_valid to indicate the data is valid for output

2023-10-20 14:57 UTC, xiaoling-yi commented on src/test/scala/gemm/TestLargeGemm.scala
> +        dut.clock.step(5)
Hi @rgantonio , I found I use the different tests with different purposes. It is not easy to write them in a single function. Maybe we just keep this?

2023-10-20 16:04 UTC, rgantonio commented on src/test/scala/gemm/TestLargeGemm.scala
> +        dut.clock.step(5)
Ah okie. But I was thinking like making it into a function within the test? Or that doesn't make sense?

2023-10-20 16:04 UTC, rgantonio commented on src/test/scala/gemm/TestLargeGemm.scala
> +        dut.clock.step(5)
Oh never mind I think I saw why... haha

2023-10-23 07:53 UTC, xiaoling-yi commented on src/test/scala/gemm/TestLargeGemm.scala
> +        dut.clock.step(5)
Nice! Basically, I orchestrate the input value and cycles to see if the Gemm works well in different situations.

2023-10-23 07:55 UTC, xiaoling-yi commented on src/test/scala/gemm/TestLargeGemm.scala
> +        dut.clock.step(5)
Let me add more comments to clarify this!

2023-10-23 08:17 UTC, xiaoling-yi commented on docs/block_matrix_mul.png
I added another picture!

2023-10-23 09:45 UTC, JosseVanDelm requested changes
Hi @xiaoling-yi this is already a much better PR than the previous ones!
Still I have some questions comments and suggestions:
* There is still many room for misunderstanding in the README. (I'm being extra annoying on this, because I know from experience that this is very important to get right, otherwise we all will lose so much time on this!)
* From some of the tests it should be clear what is expected, right now this is is clear for me from the golden model tests, but not from the controller tests?
* You are renaming variables across the files, but you have not mentioned this in your PR description.
* I think we can write some of the tests in a more modular and explainable fashion, which should make it easier to test later.
* You should make sure the seed for random tests is set somewhere, otherwise we always test different values on each CI run...

2023-10-23 09:45 UTC, JosseVanDelm commented on README.md
> +<!-- This repository contains three GEMM versions: Base GEMM, Block GEMM, and Batch Block GEMM. -->
Could still be useful to uncomment this IMO?

2023-10-23 09:45 UTC, JosseVanDelm commented on README.md
> +Base GEMM implements General Matrix Multiply: C = A * B. Base GEMM is parameterized and its parameters are listed below. These parameters can be configured in the `main/scala/gemm/Parameter.scala` fi
GEMM in BLAS is defined as:
```c
 GEMM (&transa, &transb, &m, &n, &k, alpha, a, &lda, b, &ldb, beta, c, &ldc);
```
So this feels like a misnomer, it feels like we are implementing https://www.mlplatform.org/tosa/tosa_spec.html#_matmul instead?

2023-10-23 09:45 UTC, JosseVanDelm commented on README.md
> +In this case, the size of matrix A is (M * meshRow, K * tileSize) and the size of matrix B is (K * tileSize, N * meshCol). The size of result matrix C is (M * meshRow, N * meshCol). The GEMM accelera
```suggestion
In this case, the size of matrix A is (M * meshRow, K * tileSize) and the size of matrix B is (K * tileSize, N * meshCol). The size of result matrix C is (M * meshRow, N * meshCol). 

The GEMM accelerator uses the [Block matrix multiplication method](https://en.wikipedia.org/wiki/Block_matrix#Block_matrix_multiplication) to implement matrix multiplication in which the matrix sizes are larger than the physical GEMM array. 

To get the right results, matrixes should have the right layout in memory. In the current version, these data should be stored in memory in a continuous address style. Below is an example data layout in memory for M = 2, K = 2, and N = 2. The address of martix A, B and C should also be given.
```

2023-10-23 09:45 UTC, JosseVanDelm commented on README.md
> +![](./docs/block_matrix_mul.png)
I don't understand this figure.
What is `a11`, what is `a12`? Can we only multiply square matrices?
What is on the x-axis? Is this the memory address? Is this a different bank? Is this the matrix index?
What does the arrow (there's no arrow head) represent? In which direction is the arrow going?
Why is one arrow blue, and the other one orange?

2023-10-23 09:45 UTC, JosseVanDelm commented on src/main/scala/gemm/GemmArray.scala
@xiaoling-yi can you be a bit more upfront on what you are refactoring and why you are doing this?
In the future it would be nice to refactor only the part that this PR addresses.
Refactors make the diff very difficult to read and make it difficult to review your actual changes.
Your PR description does not mention any refactoring at all, so this is a bit misleading

2023-10-23 09:45 UTC, JosseVanDelm commented on README.md
> +| Signals | Width | Dir | Discription |
```suggestion
| Signals | Width | Dir | Description |
```

2023-10-23 09:45 UTC, JosseVanDelm commented on README.md
> +The Block GEMM is built with the Base GEMM. It takes in the M, K, and N configurations.
Could you be a bit more explicit about the fact that M, K and N set the size of the block gemm and not the individual elements of the block gemm? In the small GEMM the matrix A and B are always of a certain size, and in this part of the documentation, their size suddenly changes?

2023-10-23 09:45 UTC, JosseVanDelm commented on README.md
> +![](./docs/block_matrix_mul.png)
It seems the figure shows the M=4, N=4 and K=4 case, and not M=2, K=2 and N =2?

2023-10-23 09:45 UTC, JosseVanDelm commented on src/test/scala/gemm/MatrixlibLarge.scala
> +    val N = rand.between(1, 10)
Feels like a good idea here to also use testparameters to set the value of 10, similar to Parameters.scala?

2023-10-23 09:45 UTC, JosseVanDelm commented on src/test/scala/gemm/MatrixlibLarge.scala
> +  def SpliteLargeMatrx(
```suggestion
  def SplitLargeMatrx(
```

2023-10-23 09:45 UTC, JosseVanDelm commented on src/test/scala/gemm/TestLargeGemm.scala
> +          val (size_M, size_K, size_N) = MatrixLibLarge.GenRandSizeTest()
Are you setting the seed for the random testing anywhere?
Otherwise testing is not reproducible accross CI runs?

2023-10-23 09:45 UTC, JosseVanDelm commented on src/test/scala/gemm/TestLargeGemm.scala
> +        dut.io.ctrl.ptr_addr_c_i.poke(4)
I'm wondering whether it makes sense to rewrite and factor out this bit, since it reappears in this code at least 3 times?

2023-10-23 09:45 UTC, JosseVanDelm commented on src/test/scala/gemm/TestLargeGemm.scala
> +        def LargeGemmRandomTets() = {
```suggestion
        def LargeGemmRandomTest() = {
```

2023-10-23 09:45 UTC, JosseVanDelm commented on src/test/scala/gemm/TestLargeGemm.scala
> +        val TestLoop = 2
Seems also like a useful value to put into some parameters file

2023-10-23 09:45 UTC, JosseVanDelm commented on src/main/scala/gemm/LargeGemm.scala
> +  val sIDLE :: sREAD :: sREAD_DONE :: Nil = Enum(3)
What do these states represent?
Would be nice to have some comments here!

2023-10-23 09:45 UTC, JosseVanDelm commented on src/main/scala/gemm/LargeGemm.scala
> +  }
This looks quite complex:
* I can see that we have a test for this, but the test is quite difficult to read, and so it is very difficult for me to figure out how this part works?
* Can we rewrite this in a more readable fashion?
* It mentions K read counter, but I don't know what a K read counter is?
Can you be a bit more explicit:
E.g. counter that increments the address to be read from memory in block matrix multiplication mode, responsible for incrementing the counter for the K dimension of the blocked matrix mutiplication
?

2023-10-26 08:06 UTC, xiaoling-yi commented on README.md
> +<!-- This repository contains three GEMM versions: Base GEMM, Block GEMM, and Batch Block GEMM. -->
Yes, because we do not have Batch Block GEMM get.

2023-10-26 08:06 UTC, xiaoling-yi commented on README.md
> +Base GEMM implements General Matrix Multiply: C = A * B. Base GEMM is parameterized and its parameters are listed below. These parameters can be configured in the `main/scala/gemm/Parameter.scala` fi
I donn't know...

2023-10-26 08:09 UTC, xiaoling-yi commented on src/test/scala/gemm/MatrixlibLarge.scala
> +    val N = rand.between(1, 10)
Maybe we need a new file named TestParameters.scala?

2023-10-26 09:47 UTC, xiaoling-yi commented on README.md
> +![](./docs/block_matrix_mul.png)
More illustration added..

2023-10-26 13:50 UTC, xiaoling-yi commented
Hi @JosseVanDelm @guilherme-paim @rgantonio ! 

I addressed almost all the comments you pointed out except for the microarchitecture figure because I think it is still a bit hard for me to draw a beautiful and detailed microarchitecture figure. I will try my best to draw it later on! This has been added it the issue too.

Please review this RP again and give comments. Thanks!

2023-10-26 14:15 UTC, JosseVanDelm commented
@xiaoling-yi you can use this magical button to re-request a review:
![image](https://github.com/KULeuven-MICAS/snax-gemm/assets/24391306/579d7aba-9d79-4ec6-b2c0-660ee6e17e3f)
@rgantonio and @guilherme-paim I'm still a bit swamped with the double buffering example.
Can you guys take over the first re-reviews please?

2023-10-27 06:40 UTC, rgantonio approved these changes
I am OK with the documentation. It's quite detailed honestly and I learned about the block gemm 😄  so good job @xiaoling-yi

2023-10-27 06:40 UTC, rgantonio commented on README.md
> +In this case, the size of matrix A is (M' = M * meshRow, K' = K * tileSize) and the size of matrix B is (K' = K * tileSize, N' = N * meshCol). The size of result matrix C is (M' = M * meshRow, N' = N
```suggestion
In this case, the size of matrix A is (`M' = M * meshRow`, `K' = K * tileSize`) and the size of matrix B is (`K' = K * tileSize`, `N' = N * meshCol`). The size of result matrix C is (`M' = M * meshRow, N' = N * meshCol`) as shown below.
```

Just so that the formatting is consistent 🍰

2023-10-27 06:40 UTC, rgantonio commented on README.md
> +In this case, the size of matrix A is (M' = M * meshRow, K' = K * tileSize) and the size of matrix B is (K' = K * tileSize, N' = N * meshCol). The size of result matrix C is (M' = M * meshRow, N' = N
Actually do it for others too 😉

2023-10-27 06:40 UTC, rgantonio commented on docs/general_mm.png
What if you made this vertical? Do you think it would be better?

2023-10-27 06:40 UTC, rgantonio commented on src/test/scala/gemm/TestLargeGemm.scala
> +        dut.io.ctrl.ptr_addr_c_i.poke(4)
+1 haha I can't remember what we discussed before @xiaoling-yi why you initially thought it wasn't OK to make it into a function before.

2023-10-27 07:14 UTC, xiaoling-yi commented on src/test/scala/gemm/TestLargeGemm.scala
> +        dut.io.ctrl.ptr_addr_c_i.poke(4)
> // Simple test to see if the BlockGemmController work well with manual configuration
// In this test, the M, K, N are setted mannually to see the behavior of the Block Gemm and to check if the control signals works well
// Testing what if the start_do_i is asserted when the Block Gemm is busy
// And also orchestrating the data_valid_i to see if the Gemm works well under different situations
// Finally checking the output manually in the waveform

This a a manual test for different situations. Not easy to write in a uniform function. And no necessity!

2023-10-27 07:24 UTC, xiaoling-yi commented on docs/general_mm.png
Discussed offline!

2023-10-30 08:53 UTC, guilherme-paim approved these changes
Good Job Xiaoling !

2023-10-30 09:28 UTC, JosseVanDelm requested changes
Hi, I've added some minor comments for clarity but this already looks so much better @xiaoling-yi !

2023-10-30 09:28 UTC, JosseVanDelm commented on README.md
> +Each row of the GEMM array takes in the corresponding row of matrix A, eg., all the tiles in row ith takes in the ith row of matrix A. And each column of the GEMM array takes in the corresponding col
```suggestion
Each row of the GEMM array takes in the corresponding row of matrix A, i.e., all the tiles in the ith row take in the ith row of matrix A. And each column of the GEMM array takes in the corresponding column of matrix B, i.e., all the tiles in the jth column take in the jth column of matrix B. This process is shown in the figure below in detail.
```

2023-10-30 09:28 UTC, JosseVanDelm commented on README.md
> +The base GEMM also has an accumulation option. If the signal `accumulate` is one, then the accumulator register will store the current result. If the signal `accumulate` is zero, then the accumulator
```suggestion
The base GEMM also has an accumulation option. If the signal `accumulate` is one, then the accumulator register will retain it's current result. If the signal `accumulate` is zero, then the accumulator register will clear itself.
This option is useful for using the base GEMM for software-managed block matrix multiplication.

```

2023-10-30 09:28 UTC, JosseVanDelm commented on README.md
> +The base GEMM also has an accumulation option. If the signal `accumulate` is one, then the accumulator register will store the current result. If the signal `accumulate` is zero, then the accumulator
Do you think this is a useful comment to add here @xiaoling-yi ?

2023-10-30 09:28 UTC, JosseVanDelm commented on README.md
> +Take a Block Gemm with hardware parmaters: `meshRow == tileSize == meshCol == 8` as an example, the `M, K, and N` should be configured as `4, 2, and 3` respectively if we want to do the block matrix
```suggestion
Take a Block Gemm with hardware parameters: `meshRow == tileSize == meshCol == 8` as an example, the `M, K, and N` should be configured as `4, 2, and 3` respectively if we want to do the block matrix multiplication with `C(32,24) = A(32,16) * B(16,24), M’ = 32, K’ = 16, N’ = 24`. The block matrix multiplication is illustrated in the picture below. With: 
```

2023-10-30 09:28 UTC, JosseVanDelm commented on README.md
> +To get the right results, matrices should have the right layout in memory. The address of martix A, B, and C should also be given when configuring the Block Gemm. In the current version, these data s
Do you mean that A and B have to be stored right next to each other? Then I would put it like this:
```suggestion
To get the right results, the input matrices should have the right layout in memory. The address of matrix A, B, and C should also be given when configuring the Block Gemm. In the current version, the data of A and B should be stored contiguously in memory. 
```

2023-10-30 09:28 UTC, JosseVanDelm commented on README.md
> +To get the right results, matrices should have the right layout in memory. The address of martix A, B, and C should also be given when configuring the Block Gemm. In the current version, these data s
If you mean that A and B's elements have to be stored right next to eachother I would put it like this:
```suggestion
To get the right results, the input matrices should have the right layout in memory. The address of matrix A, B, and C should also be given when configuring the Block Gemm. In the current version, the data of A and B should be stored in memory with a stride of 1. 
```

2023-10-30 09:28 UTC, JosseVanDelm commented on README.md
> +To get the right results, the matrix A should be arranged as M<sub>3</sub> K<sub>4</sub> M<sub>8</sub> K<sub>8</sub>. B should be arranged as N<sub>5</sub> K<sub>4</sub> N<sub>8</sub> K<sub>8</sub>.
```suggestion
To get the right results for `M = 3`, `K=4` and `N=5` , the matrix A should be arranged as M<sub>3</sub> K<sub>4</sub> M<sub>8</sub> K<sub>8</sub>. B should be arranged as N<sub>5</sub> K<sub>4</sub> N<sub>8</sub> K<sub>8</sub>. C should be arranged as M<sub>3</sub> N<sub>5</sub> M<sub>8</sub> N<sub>8</sub>. Take matrix A for example, the innermost is 8 elements in the K dimension, then is the 8 rows in the M dimension, then is 4 big columns in the K dimension, and the outermost is 3 big rows in the M dimension.
```

2023-10-30 09:28 UTC, JosseVanDelm commented on README.md
@xiaoling-yi in your presentations you mentioned some prior work that your work is inspired by.
I feel like we should add some acknowledgements/references to the bottom of this README file to reference to those. What do you think?

2023-10-30 09:28 UTC, JosseVanDelm commented on src/main/scala/gemm/LargeGemm.scala
> +// The BlockGemmControllerIO's port declaration. Detailed explanation of these ports can be found in the README
Very nice!

2023-10-30 09:28 UTC, JosseVanDelm commented on src/main/scala/gemm/LargeGemm.scala
> +  // Write counter update write_counter_next from according to the io.data_valid_o
I don't understand this sentence

2023-10-30 09:28 UTC, JosseVanDelm commented on src/main/scala/gemm/LargeGemm.scala
> +  // We need write_counter and write_counter_next beacuse
```suggestion
  // We need write_counter and write_counter_next because
```

2023-10-30 09:28 UTC, JosseVanDelm commented on src/main/scala/gemm/LargeGemm.scala
> +  // but the write address is generated accoridng to the previous cycle write_counter_next
```suggestion
  // but the write address is generated according to the previous cycle write_counter_next
```

2023-10-30 09:28 UTC, JosseVanDelm commented on src/main/scala/gemm/LargeGemm.scala
> +  // accumulate_counter for geenrating the accumulation signal for BaseGemm
```suggestion
  // accumulate_counter for generating the accumulation signal for BaseGemm
```

2023-10-30 09:28 UTC, JosseVanDelm commented on src/test/scala/gemm/TestLargeGemm.scala
> +// Simple test to see if the BlockGemmController work well with manual configuration
```suggestion
// Simple test to see if the BlockGemmController works well with manual configuration
```

2023-10-30 09:28 UTC, JosseVanDelm commented on src/test/scala/gemm/TestLargeGemm.scala
@xiaoling-yi maybe we should also rename this file to TestBlockGemm.scala?

2023-10-30 09:54 UTC, merged