Xiaoling/add tcdm ports
KULeuven-MICAS/snax-gemm pull request #15
Opened 2023-10-31 10:41 UTC by xiaoling-yi

In this PR, we add the following:
* the source code of multiple numbers of (8, 16, and 32) TCDM ports support and multiple cycle output
* the automatic test of Gemm with multiple numbers of TCDM ports but still output in one cycle
* the manual test for Gemm with multiple numbers of TCDM ports  and multiple cycle output
* the golden model for Gemm with multiple numbers of TCDM ports but still output in one cycle
* the relevant documentation

2023-11-09 14:44 UTC, guilherme-paim requested changes
Hi Xiaoling! Good Job.

2023-11-13 14:19 UTC, rgantonio requested changes
Please fix some stuff :>

2023-11-13 14:19 UTC, rgantonio commented on README.md
Change installation description into the `install.sh` instead ❤️‍🔥 ❤️‍🔥 ❤️‍🔥 ❤️‍🔥

2023-11-13 14:19 UTC, rgantonio commented on src/snax_gemm_wrapper.sv
> +    end
@rgantonio plez think about this 😄

2023-11-13 14:19 UTC, rgantonio commented on Makefile
> +CHISEL_MODULE = BatchGemmTCDMWritePortsMultiOutput
Change to BatchGemmSnaxTop

2023-11-13 14:40 UTC, rgantonio approved these changes
Hoorah! 😄

2023-11-13 15:31 UTC, xiaoling-yi commented on src/snax_gemm_wrapper.sv
I will add it in the next PR! This RP is ready super big!

2023-11-13 15:32 UTC, xiaoling-yi commented on src/snax_gemm_wrapper.sv
> +  localparam int unsigned Address_A_CSR = 32'h3c0;
All localparam is changed to CamelCase as verible suggests!

2023-11-13 15:47 UTC, merged