doc: init readme
KULeuven-MICAS/snax-gemm pull request #17
Opened 2023-11-21 10:40 UTC by xiaoling-yi

In this PR, we update the documentation!

2023-11-22 09:55 UTC, JosseVanDelm requested changes
Hi @xiaoling-yi I overall really like this PR, but I'm afraid Apache 2.0 might not be the right license, can we discuss this later?

2023-11-22 09:55 UTC, JosseVanDelm commented on LICENSE
I'm not a legal expert, but I think Apache is generally regarded as a software license, and not as a hardware license. You might want to look at http://solderpad.org/licenses/ or https://cern-ohl.web.cern.ch/
Snitch seems to use Apache 2.0 for sw, and SHL 0.51 for hardware

2023-11-22 09:55 UTC, JosseVanDelm commented on LICENSE
> +   Copyright [yyyy] [name of copyright owner]
Regardless of the license type, this field should be filled in

2023-11-22 09:55 UTC, JosseVanDelm commented on README.md
> +int Bacth, int M, int N, int K,
```suggestion
int Batch, int M, int N, int K,
```

2023-11-23 12:27 UTC, guilherme-paim approved these changes
Ok ! Nice Xiaoling !!!

2023-11-29 09:32 UTC, merged