sw: Add scalafmt configuration file
KULeuven-MICAS/snax-gemm pull request #5
Opened 2023-10-12 14:35 UTC by xiaoling-yi

Add scalafmt autoformatter for really  cool style

2023-10-12 14:37 UTC, JosseVanDelm requested changes
Add github action for scalafmt

2023-10-13 08:26 UTC, xiaoling-yi commented
Hi Josse, the stb-scalafmt has been added successfully.

2023-10-13 11:02 UTC, JosseVanDelm requested changes
Hi @xiaoling-yi,

The tests you setup are not running correctly.
I suggest the following:
* remove the actual SBT test and firtool installation from this PR, let's just focus on formatting instead
* Why do we need to test for java 8, 11, and 17? I think pinning to one version should be okay :smile: , at least for now!
* Are you sure you are correctly checking out the repo with fetch-depth=0? Otherwise the format tests might return a false positive!

2023-10-13 11:17 UTC, xiaoling-yi commented on .github/workflows/unit_test.yml
> +        java-version: [8, 11, 17]
I deleted version 8 and 17.

2023-10-13 11:20 UTC, xiaoling-yi commented on .github/workflows/unit_test.yml
> +          fetch-depth: 0
Oh, I have changed fetch-depth to 1.

2023-10-13 11:20 UTC, xiaoling-yi commented on .github/workflows/unit_test.yml
> +        run: sbt test
Ok. no problem.

2023-10-13 11:25 UTC, JosseVanDelm approved these changes
This looks much better!

@xiaoling-yi why are we using version 11 specifically? Is this the version that works best for chisel?

2023-10-13 11:51 UTC, xiaoling-yi commented
version 17 also works. It is compatible with our Scala and Chisel versions.

2023-10-13 12:17 UTC, merged