doc: add readme
KULeuven-MICAS/snax-gemm pull request #7
Opened 2023-10-16 11:51 UTC by xiaoling-yi

This RP adds a detailed readme for the GEMM accelerator, including:
* Microarchitecture
* Functional description
* Unit test description

2023-10-16 13:33 UTC, JosseVanDelm requested changes
This is really great!

Please:
* Add figures
* Remove unimplemented stuff (for now!)

2023-10-16 13:33 UTC, JosseVanDelm commented on README.md
> +to integrate into the [SNAX core](https://github.com/KULeuven-micas/snitch_cluster). This repository contains the chisel src file and unit test of the GEMM accelerator.
```suggestion
to integrate into the [SNAX core](https://github.com/KULeuven-micas/snitch_cluster). This repository contains the chisel sources and unit tests for the GEMM accelerator.
```

2023-10-16 13:33 UTC, JosseVanDelm commented on README.md
> +In this case, the size of matrix A is (M * meshRow, K * tileSize) and the size of matrix B is (K * tileSize, N * meshCol). The size of result matrix C is (M * meshRow, N * meshCol). The GEMM accelera
```suggestion
In this case, the size of matrix A is (M * meshRow, K * tileSize) and the size of matrix B is (K * tileSize, N * meshCol). The size of result matrix C is (M * meshRow, N * meshCol). The GEMM accelerator uses [Block matrix multiplication](https://en.wikipedia.org/wiki/Block_matrix#Block_matrix_multiplication) method to implement matrix multiplication in which the matrix sizes are much larger than the physical GEMM array. To get the right results, matrixes should have the right layout in memory. Below is an example data layout in memory for M = 2, K = 2, and N = 2. 
```

2023-10-16 13:33 UTC, JosseVanDelm commented on README.md
> +In this case, the size of matrix A is (M * meshRow, K * tileSize) and the size of matrix B is (K * tileSize, N * meshCol). The size of result matrix C is (M * meshRow, N * meshCol). The GEMM accelera
Can you split this into multiple lines please?

2023-10-16 13:33 UTC, JosseVanDelm commented on README.md
> +This repository also contains some unit tests for each version of GEMM to do the numerical test. The unit tests are also written in Chisel. Firstly, the random input matrixes and random size configur
```suggestion
This repository also contains some unit tests for each version of GEMM to do the numerical test. The unit tests are also written in Chisel. Firstly, random input matrices and random size configurations are generated. Then these matrices and configurations are fed into the GEMM accelerator. After the computation, the output result of the GEMM accelerator will be compared with the golden model in Scala.
```

2023-10-16 13:33 UTC, JosseVanDelm commented on README.md
> +Following this quick start to set up the Chsiel environment and run the unit test of the GEMM accelerator.
```suggestion
## Quickstart
Follow this quickstart to set up the Chisel environment and run the unit tests of the GEMM accelerator.
```

2023-10-16 13:33 UTC, JosseVanDelm commented on README.md
> +```
Can we add this when this functionality is added maybe?

2023-10-16 13:47 UTC, xiaoling-yi commented on README.md
> +```
Sure!

2023-10-18 13:14 UTC, JosseVanDelm commented
Closing this for now in favor of #8 and future PRs

2023-10-18 13:14 UTC, closed without merging