Add Base GEMM
KULeuven-MICAS/snax-gemm pull request #8
Opened 2023-10-17 09:38 UTC by xiaoling-yi

This RP adds the Base GEMM:
* Add comments to the source and test file
* Add Unit test for the Base GEMM
* Add documentary for the Base GEMM

2023-10-17 09:48 UTC, JosseVanDelm requested changes
Hi @xiaoling-yi, this seems to remove all previously existing files and replace them with entirely new files, even though they are not completely new? Could you make the changes in the previously existing files please? Otherwise it kind of defeats the purpose of using Git

2023-10-17 09:51 UTC, xiaoling-yi commented
Hi @JosseVanDelm , the file names have been changed to more format ones. The code is based on the previously existing files.

2023-10-17 09:56 UTC, JosseVanDelm commented
I see, but now I can not properly review the changes. The diff just shows completely new files, and I can not see what you added/removed. Can we make a seperate PR for the refactoring of the names later please, that keeps a proper blame too?

2023-10-17 09:59 UTC, xiaoling-yi commented
Hi @JosseVanDelm , Yes we can. How can we do this?

2023-10-17 13:43 UTC, JosseVanDelm commented
Files are renamed now and ready for review!

2023-10-17 14:25 UTC, JosseVanDelm requested changes
Hi @xiaoling-yi this is a really good PR! It is going in the right direction!

Some major comments:
* You seem a bit inconsistent with your use of `SInt` and `UInt`? throughout your design.
* The description for your PR could be a bit more elaborate, because this one adds a lot of extra stuff: you add a golden model, unit tests, and an accumulate input! especially the golden model and accumulate input are mentioned nowhere in your PR description.
* You forgot to attach your schematics in this PR
* Your docs and parameters allow parameterizing your IP, but you only test for the default case, and the test itself is not parameterizable.
* You add a lot of commented out prints in your test. These are not available in the automated tester. I'm wondering whether we should remove these calls.

2023-10-17 14:25 UTC, JosseVanDelm commented on src/main/scala/gemm/gemm.scala
>        Vec(GEMMConstant.tileSize, UInt(GEMMConstant.input.W))
Why are we using `SInt` for the type of `c_o` but not for `a_i` or `b_i`?

2023-10-17 14:25 UTC, JosseVanDelm commented on src/test/scala/gemm/MatrixlibBase.scala
> +  }
Why is this function here twice?

2023-10-17 14:25 UTC, JosseVanDelm commented on src/main/scala/gemm/Parameter.scala
>    def input = 8
Both your documentation and this parameter file mention the possibility to change the bitwidth of this number, but your test hardcodes these values inside the types (e.g. use `Byte` for inputs) for for the golden model.
I feel like we should either:
* add a disclaimer that only these datatypes are tested and supported (easy)
* add support for random datatypes in the golden model and tests (hard!)
I'd definitely stick with the first option for now (and in this PR please!)

2023-10-17 14:25 UTC, JosseVanDelm commented on src/test/scala/gemm/MatrixlibBase.scala
> +  def MarixMul_1D(
```suggestion
  def MatrixMul_1D(
```

2023-10-17 14:25 UTC, JosseVanDelm commented on src/test/scala/gemm/MatrixlibBase.scala
> +  def MarixMul_2D(
```suggestion
  def MatrixMul_2D(
```

2023-10-17 14:25 UTC, JosseVanDelm commented on src/test/scala/gemm/MatrixlibBase.scala
> +  // Matrix multiplication with 2 dimension Array[Array[Byte]] data type
This function does not seem to be used?

2023-10-18 09:30 UTC, xiaoling-yi commented on README.md
> +![](./docs/microarch.png)
Added!

2023-10-18 09:35 UTC, xiaoling-yi commented on src/main/scala/gemm/gemm.scala
> +      .asSInt
It is strange but it is generated by scalamft.

2023-10-18 10:38 UTC, xiaoling-yi commented on src/test/scala/gemm/MatrixlibBase.scala
> +  // Matrix multiplication with 2 dimension Array[Array[Byte]] data type
removed!

2023-10-18 12:21 UTC, xiaoling-yi commented on src/main/scala/gemm/gemm.scala
> +  val accumulation_reg = RegInit(0.S(GEMMConstant.accumulate.W))
Rename var to be more clear about the data type

2023-10-18 12:22 UTC, xiaoling-yi commented on src/main/scala/gemm/gemm.scala
> +  val chek_data_in_valid_reg = RegInit(0.B)
Changed!

2023-10-18 13:01 UTC, rgantonio approved these changes
Nice work! Just an FYI, @xiaoling-yi  and @rgantonio discussed in person for speed up purposes 😄 

Issues were made for TODO tasks.

@xiaoling-yi please make the filename changes you mentioned earlier.

2023-10-18 13:08 UTC, JosseVanDelm approved these changes
Thanks @rgantonio !

2023-10-18 13:09 UTC, merged